// grid dummy data
var dummyData = {
	// "Madlo ke dveřím":"<li class=\"product\"><img src=\"images/madlo_ke_dverim/image-1.jpg\" height=\"192\" width=\"383\" alt=\"kované madlo ke dveřím - pohled zepředu\" title=\"kované madlo ke dveřím - pohled zepředu\"></li><li class=\"product\"><img src=\"images/madlo_ke_dverim/image-2.jpg\" alt=\"kované madlo ke dveřím - pohled zleva\" title=\"kované madlo ke dveřím - pohled zleva\"></li><li class=\"product\"><img src=\"images/madlo_ke_dverim/image-3.jpg\" alt=\"kované madlo ke dveřím - pohled zprava\" title=\"kované madlo ke dveřím - pohled zprava\"></li><li class=\"product\"><img src=\"images/madlo_ke_dverim/image-4.jpg\" alt=\"kované madlo ke dveřím - pohled zprava 2\" title=\"kované madlo ke dveřím - pohled zprava 2\"></li><li class=\"product\"><img src=\"images/madlo_ke_dverim/image-1.jpg\" height=\"192\" width=\"383\" alt=\"kované madlo ke dveřím - pohled zepředu\" title=\"kované madlo ke dveřím - pohled zepředu\"></li><li class=\"product\"><img src=\"images/madlo_ke_dverim/image-1.jpg\" height=\"192\" width=\"383\" alt=\"kované madlo ke dveřím - pohled zepředu\" title=\"kované madlo ke dveřím - pohled zepředu\"></li><li class=\"product\"><img src=\"images/madlo_ke_dverim/image-1.jpg\" height=\"192\" width=\"383\" alt=\"kované madlo ke dveřím - pohled zepředu\" title=\"kované madlo ke dveřím - pohled zepředu\"></li><li class=\"product\"><img src=\"images/madlo_ke_dverim/image-2.jpg\" alt=\"kované madlo ke dveřím - pohled zleva\" title=\"kované madlo ke dveřím - pohled zleva\"></li><li class=\"product\"><img src=\"images/madlo_ke_dverim/image-3.jpg\" alt=\"kované madlo ke dveřím - pohled zprava\" title=\"kované madlo ke dveřím - pohled zprava\"></li>",

	"Madlo ke dveřím":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Schodišťové zábradlí":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Věšák s ventily - malý":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Věšák s ventily - velký":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Velký lustr":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Kovaný lustr kombinovaný s mědí":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Zábradlí":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Gril na stůl - kovaný":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Okovaná žulová deska na gril":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Opasek":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>",

	"Svícen - chobotnička":"<li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li><li class=\"product\"><img src=\"images/default.jpg\" height=\"192\" width=\"383\" alt=\"\" title=\"\"></li>"

}